# Generated by Django 2.2 on 2020-06-19 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('productId', models.AutoField(primary_key=True, serialize=False)),
                ('productName', models.CharField(max_length=100)),
                ('productCategory', models.TextField()),
                ('productPrice', models.FloatField()),
                ('productPreviewDesc', models.CharField(max_length=200, null=True)),
                ('productFullDesc', models.CharField(max_length=400, null=True)),
            ],
        ),
    ]
