# Generated by Django 2.2 on 2020-06-25 19:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_testorder'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestOrder',
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
